Make tests pass at any timezone
akosbalasko/yarle pull request #44
Opened 2020-08-30 15:51 UTC by rodbv

Fixes #43 

Changed fixture MD files so that they expect times on Europe/London timezone (offset +01:00), and mocked this timezone on yarle.spec.ts.

This ensures that these tests will pass no matter what is the timezone of the computer running the tests.

2020-08-30 17:15 UTC, rodbv commented
Also fixed issues with the 2 tests that had it.skip. All tests running and passing now! 👍

2020-08-31 14:43 UTC, akosbalasko requested changes
Hi! 
First of all, thank you for your fork + fixes, I really appreciate them! 
I've got only one short modification request, as you see, then I'm glad to merge your fix!
Cheers,
akos

2020-08-31 14:43 UTC, akosbalasko commented on package.json
> +    "timezone-mock": "^1.1.1"
Please remove hat from the dependency, just to prohibit that a breaking change in a future-version of timezone breaks the conversion. Thank you!

```suggestion
    "timezone-mock": "1.1.1"
```

2020-08-31 14:43 UTC, akosbalasko commented on test/yarle.spec.ts
> +    mockTimezone.register('Europe/London');
Thank you for this, I didn't know this package.

2020-09-01 12:26 UTC, akosbalasko approved these changes

2020-09-01 12:33 UTC, merged